name: Deploy to vercel

on:
    push:
        branches:
            - main
            - feature/*
    pull_request_target:
jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout code
              uses: actions/setup-node@v3
              with:
                node-version: '16'

            - name: Install dependencies
              run: npm install

            - name: Run Build
              run: npm build
              
            - name: Run test
              run: npm test

            - name: Vercel Deploy process
              env:
                VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
              run: |
                npm install -g vercel
                vercel --prod --token  $VERCEL_TOKEN  

